// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdqcY5esV6JeHWdNKZGSgP_YrltMpxjPQ',
    appId: '1:58775303388:web:0c98c6f7c86466ac05b019',
    messagingSenderId: '58775303388',
    projectId: 'flutter-login-32d49',
    authDomain: 'flutter-login-32d49.firebaseapp.com',
    storageBucket: 'flutter-login-32d49.appspot.com',
    measurementId: 'G-75VNKN8LZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6pWaaKoqHFyT4CRvqOFCrtdWee2bCxqo',
    appId: '1:58775303388:android:a347c35aa48bea8505b019',
    messagingSenderId: '58775303388',
    projectId: 'flutter-login-32d49',
    storageBucket: 'flutter-login-32d49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeUog4vRtCdIayUl_A-w7XG1HqZiGh1OQ',
    appId: '1:58775303388:ios:13ba5ba9ea70118905b019',
    messagingSenderId: '58775303388',
    projectId: 'flutter-login-32d49',
    storageBucket: 'flutter-login-32d49.appspot.com',
    iosBundleId: 'com.example.recycleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeUog4vRtCdIayUl_A-w7XG1HqZiGh1OQ',
    appId: '1:58775303388:ios:13ba5ba9ea70118905b019',
    messagingSenderId: '58775303388',
    projectId: 'flutter-login-32d49',
    storageBucket: 'flutter-login-32d49.appspot.com',
    iosBundleId: 'com.example.recycleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdqcY5esV6JeHWdNKZGSgP_YrltMpxjPQ',
    appId: '1:58775303388:web:2f11d5c81e4c15c705b019',
    messagingSenderId: '58775303388',
    projectId: 'flutter-login-32d49',
    authDomain: 'flutter-login-32d49.firebaseapp.com',
    storageBucket: 'flutter-login-32d49.appspot.com',
    measurementId: 'G-WDZECHVZ2B',
  );
}
