# This is a basic workflow to help you get started with Actions

name: Flutter Build and Upload Android APK

# Controls when the workflow will run
on: workflow_dispatch
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: microsoft

      - name: Install yq
        uses: mikefarah/yq@v4.42.1

      - name: Get pubspec version
        id: get_flutter_app_version
        run: |
          VERSION=$(yq .version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' pubspec.yaml | head -n 1)
          echo "TAG_VERSION=$VERSION" >> $GITHUB_OUTPUT
  
      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "v${{ steps.get_flutter_app_version.outputs.TAG_VERSION }}" >/dev/null 2>&1; then
            # Tag exists, increment version
            IFS='.' read -r -a VERSION_PARTS <<< "${{ steps.get_flutter_app_version.outputs.TAG_VERSION }}"
            PATCH_VERSION=$((VERSION_PARTS[2]+1))
            NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH_VERSION"
            echo "NEW_TAG_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
          else
            # Tag does not exist, use the current version
            echo "NEW_TAG_VERSION=${{ steps.get_flutter_app_version.outputs.TAG_VERSION }}" >> $GITHUB_OUTPUT
          fi
  
      - name: Create git tag
        run: |
          git tag "v${{ steps.check_tag.outputs.NEW_TAG_VERSION }}"

      - name: Install Flutter          
        uses: subosito/flutter-action@v2
        with:
          channel: 'main'

      - name: Get Flutter dependencies    
        run: flutter pub get

      - name: Build APK Release             
        run: flutter build apk --release

      - name: Build an AppBundle          
        run: flutter build appbundle --release

      - name: Save APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/*.apk

      - name: Save APPBUNDLE to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-appbundle
          path: build/app/outputs/bundle/release/*.aab

      - name: Create or Update GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/bundle/release/*.aab,build/app/outputs/flutter-apk/*.apk
          tag: "v${{ steps.check_tag.outputs.NEW_TAG_VERSION }}" # 使用动态生成的标签
          generateReleaseNotes: false
          makeLatest: legacy
          omitBody: false
          omitBodyDuringUpdate: false
          omitDraftDuringUpdate: false
          omitName: false
          omitNameDuringUpdate: false
          omitPrereleaseDuringUpdate: false
          removeArtifacts: false
          replacesArtifacts: true
          skipIfReleaseExists: false
          updateOnlyUnreleased: true  # 添加此行以在标签存在时更新发布
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Microsoft_jdk/11.0.19/x64
          JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Microsoft_jdk/11.0.19/x64
          FLUTTER_ROOT: /opt/hostedtoolcache/flutter/main-any-x64
          PUB_CACHE: /home/runner/.pub-cache


          
    # # Steps represent a sequence of tasks that will be executed as part of the job
    # steps:
    #   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #   - uses: actions/checkout@v4

    #   # Runs a single command using the runners shell
    #   - name: Run a one-line script
    #     run: echo Hello, world!

    #   # Runs a set of commands using the runners shell
    #   - name: Run a multi-line script
    #     run: |
    #       echo Add other actions to build,
    #       echo test, and deploy your project.
      
